version: "3"
services:
  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: react
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
  nestapp:
    container_name: nestapp
    image: nestapp:0.0.1
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
