version: "3"
services:
  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: react
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
