version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: cimg/node:12.16
        user: root
    parallelism: 5
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
      - run:
          name: Install server Dependencies
          command: cd server && npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
          paths:
            - .server/node_modules
      - run:
          name: Install Jest-cli globally
          command: npm install -g jest-cli
      - run:
          name: Install JUnit coverage reporter
          command: npm add --dev jest-junit
      - run:
          name: Create artifact directory
          command: mkdir /root/project/reports && mkdir /root/project/reports/junit
      - run:
          name: Run tests with JUnit as reporter
          command: cd server && jest auth.controller --ci --runInBand --reporters=default --reporters=jest-junit  --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT_DIR: /root/project/server/reports
      - store_test_results:
          path: /root/project/server/reports
      - store_artifacts:
          path: /root/project/server/reports/
      - codecov/upload:
          file: "./root/project/server/reports/junit.xml"
          token: $CODECOV_TOKEN
      - setup_remote_docker:
          version: 19.03.13
      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - deploy:
          name: Build and push Docker image
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t wbroderick/conduit:$TAG .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push wbroderick/conduit:$TAG

workflows: # a single workflow with a single job called build
  version: 2
  build:
    jobs:
      - build:
          context: development
