version: '3.7'
services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      - 3001:9229
    command: npm run start:dev
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/Conduit
      - /usr/src/Conduit/node_modules
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always
  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:prod
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/Conduit
      - /usr/src/Conduit/node_modules
    restart: unless-stopped
networks:
  nesjs-network:
    driver: bridge
