name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      MONGO_ATLAS_USER: ${{ secrets.MONGO_ATLAS_USER }}
      MONGO_ATLAS_PASSWORD: ${{ secrets.MONGO_ATLAS_PASSWORD }}
      MONGO_ATLAS_DB_ADDRESS: ${{ secrets.MONGO_ATLAS_DB_ADDRESS }}
      MONGO_ATLAS_DB: ${{ secrets.MONGO_ATLAS_DB }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build
        env:
          MONGO_ATLAS_USER: ${{ secrets.MONGO_ATLAS_USER }}
          MONGO_ATLAS_PASSWORD: ${{ secrets.MONGO_ATLAS_PASSWORD }}
          MONGO_ATLAS_DB_ADDRESS: ${{ secrets.MONGO_ATLAS_DB_ADDRESS }}
          MONGO_ATLAS_DB: ${{ secrets.MONGO_ATLAS_DB }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: user/app:latest
          secrets: |
            "MONGO_ATLAS_USER=${{ secrets.MONGO_ATLAS_USER }}"
            "MONGO_ATLAS_PASSWORD=${{ secrets.MONGO_ATLAS_PASSWORD }}"
            "MONGO_ATLAS_DB_ADDRESS=${{ secrets.MONGO_ATLAS_DB_ADDRESS }}"
            "MONGO_ATLAS_DB=${{ secrets.MONGO_ATLAS_DB }}"
            "JWT_SECRET=${{ secrets.JWT_SECRET }}"
