name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        env:
          MONGO_ATLAS_USER: ${{ secrets.MONGO_ATLAS_USER }}
          MONGO_ATLAS_PASSWORD: ${{ secrets.MONGO_ATLAS_PASSWORD }}
          MONGO_ATLAS_DB_ADDRESS: ${{ secrets.MONGO_ATLAS_DB_ADDRESS }}
          MONGO_ATLAS_DB: ${{ secrets.MONGO_ATLAS_DB }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: user/app:latest
          MONGO_ATLAS_USER: ${{ secrets.MONGO_ATLAS_USER }}
          MONGO_ATLAS_PASSWORD: ${{ secrets.MONGO_ATLAS_PASSWORD }}
          MONGO_ATLAS_DB_ADDRESS: ${{ secrets.MONGO_ATLAS_DB_ADDRESS }}
          MONGO_ATLAS_DB: ${{ secrets.MONGO_ATLAS_DB }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          secrets: |
            "MONGO_ATLAS_USER=${{ secrets.MONGO_ATLAS_USER }}"
            "MONGO_ATLAS_PASSWORD=${{ secrets.MONGO_ATLAS_PASSWORD }}"
            "MONGO_ATLAS_DB_ADDRESS=${{ secrets.MONGO_ATLAS_DB_ADDRESS }}"
            "MONGO_ATLAS_DB=${{ secrets.MONGO_ATLAS_DB }}"
            "JWT_SECRET=${{ secrets.JWT_SECRET }}"
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: user/app
